// Copyright 2022 Pixel Robotics.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Author: Tony Najjar
 */

#ifndef TRICYCLE_CONTROLLER__TRICYCLE_CONTROLLER_HPP_
#define TRICYCLE_CONTROLLER__TRICYCLE_CONTROLLER_HPP_

#include <chrono>
#include <cmath>
#include <deque>
#include <memory>
#include <queue>
#include <string>
#include <tuple>
#include <vector>

#include "ackermann_msgs/msg/ackermann_drive.hpp"
#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_box.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "std_msgs/msg/bool.hpp"
#include "std_msgs/msg/string.hpp"
#include "std_srvs/srv/empty.hpp"
#include "std_srvs/srv/set_bool.hpp"
#include "tf2_msgs/msg/tf_message.hpp"

#include "tricycle_controller/odometry.hpp"
#include "tricycle_controller/steering_limiter.hpp"
#include "tricycle_controller/traction_limiter.hpp"
// auto-generated by generate_parameter_library
#include "tricycle_controller/tricycle_controller_parameters.hpp"

namespace tricycle_controller
{
using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

class TricycleController : public controller_interface::ControllerInterface
{
  using Twist = geometry_msgs::msg::Twist;
  using TwistStamped = geometry_msgs::msg::TwistStamped;
  using AckermannDrive = ackermann_msgs::msg::AckermannDrive;

public:
  TricycleController();

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  CallbackReturn on_init() override;

  CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_cleanup(const rclcpp_lifecycle::State & previous_state) override;

  CallbackReturn on_error(const rclcpp_lifecycle::State & previous_state) override;

protected:
  struct TractionHandle
  {
    std::reference_wrapper<const hardware_interface::LoanedStateInterface> velocity_state;
    std::reference_wrapper<hardware_interface::LoanedCommandInterface> velocity_command;
  };
  struct SteeringHandle
  {
    std::reference_wrapper<const hardware_interface::LoanedStateInterface> position_state;
    std::reference_wrapper<hardware_interface::LoanedCommandInterface> position_command;
  };

  CallbackReturn get_traction(
    const std::string & traction_joint_name, std::vector<TractionHandle> & joint);
  CallbackReturn get_steering(
    const std::string & steering_joint_name, std::vector<SteeringHandle> & joint);
  double convert_trans_rot_vel_to_steering_angle(double v, double omega, double wheelbase);
  std::tuple<double, double> twist_to_ackermann(double linear_command, double angular_command);

  /**
   * \brief Steering hold rule: a twist that is not exactly zero but below the
   * steering_hold thresholds carries no motion, so keep the last steering
   * command and command zero wheel speed instead of converting it.
   * \return true if the hold was applied
   */
  bool apply_steering_hold(
    double linear_command, double angular_command, double & alpha, double & Ws);

  /**
   * \brief Collect churn evidence from the steering demand while stationary and
   * maintain the churn episode state (start / end, notifications).
   * \param evidence_demand false for demands that carry no churn evidence
   *        (spin-rule +-90 deg for v == 0, steering hold); they are skipped
   */
  void update_churn_monitor(
    double alpha_demand, bool stationary, bool evidence_demand, double now);

  /**
   * \brief Debounce the steering demand while the churn filter is active.
   * \param [out] settled true if the raw demand agrees with the forwarded target
   * \return the steering target to forward
   */
  double churn_filter(double alpha_demand, double now, double last_steering_cmd, bool & settled);

  void publish_churn_state(bool active, const std::string & text);

  // Parameters from ROS for tricycle_controller
  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // HACK: put into vector to avoid initializing structs because they have no default constructors
  std::vector<TractionHandle> traction_joint_;
  std::vector<SteeringHandle> steering_joint_;

  std::shared_ptr<rclcpp::Publisher<AckermannDrive>> ackermann_command_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<AckermannDrive>>
    realtime_ackermann_command_publisher_ = nullptr;

  Odometry odometry_;

  std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
    realtime_odometry_publisher_ = nullptr;

  std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_ =
    nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
    realtime_odometry_transform_publisher_ = nullptr;

  // Timeout to consider cmd_vel commands old
  std::chrono::milliseconds cmd_vel_timeout_{500};

  bool subscriber_is_active_ = false;
  rclcpp::Subscription<TwistStamped>::SharedPtr velocity_command_subscriber_ = nullptr;

  realtime_tools::RealtimeBox<std::shared_ptr<TwistStamped>> received_velocity_msg_ptr_{nullptr};
  std::shared_ptr<TwistStamped> last_command_msg_;

  rclcpp::Service<std_srvs::srv::Empty>::SharedPtr reset_odom_service_;
  rclcpp::Service<std_srvs::srv::SetBool>::SharedPtr set_exact_mode_service_;

  std::queue<AckermannDrive> previous_commands_;  // last two commands

  // speed limiters
  TractionLimiter limiter_traction_;
  SteeringLimiter limiter_steering_;
  SteeringLimiter limiter_steering_low_speed_;
  SteeringLimiter limiter_steering_stationary_;

  // Low speed threshold and timer
  double low_speed_threshold_ = 0.1;  // m/s
  double stationary_time_threshold_ = 20.0;  // seconds
  double stationary_timer_ = 0.0;  // seconds

  bool use_exact_mode_ = false;
  double exact_mode_threshold_ = M_PI / 6;

  // Stationary steering churn monitor (see update_churn_monitor / churn_filter)
  struct ChurnEvent
  {
    double time;     // seconds
    double travel;   // absolute demand change of this step [rad]
    bool reversal;   // the step reversed the direction of the previous step
  };
  std::deque<ChurnEvent> churn_events_;
  bool last_demand_valid_ = false;
  double last_demand_ = 0.0;
  int last_demand_direction_ = 0;
  bool churn_active_ = false;
  double churn_episode_start_time_ = 0.0;
  double churn_last_evidence_time_ = 0.0;
  int churn_reversals_in_window_ = 0;
  double churn_travel_in_window_ = 0.0;
  bool churn_filter_was_active_ = false;
  double debounced_target_ = 0.0;
  double pending_target_ = 0.0;
  double pending_since_ = 0.0;

  std::shared_ptr<rclcpp::Publisher<std_msgs::msg::Bool>> churn_active_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::Bool>>
    realtime_churn_active_publisher_ = nullptr;
  std::shared_ptr<rclcpp::Publisher<std_msgs::msg::String>> churn_event_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::String>>
    realtime_churn_event_publisher_ = nullptr;

  void reset_odometry(
    const std::shared_ptr<rmw_request_id_t> request_header,
    const std::shared_ptr<std_srvs::srv::Empty::Request> req,
    std::shared_ptr<std_srvs::srv::Empty::Response> res);
  void set_exact_mode(
    const std::shared_ptr<rmw_request_id_t> request_header,
    const std::shared_ptr<std_srvs::srv::SetBool::Request> req,
    std::shared_ptr<std_srvs::srv::SetBool::Response> res);
  void clip_wheel_speed_and_steering_angle(double & wheel_speed, double & steering_angle);
  void clip_speed_for_angle(double & wheel_speed, double steering_angle);
  void clip_angle_for_speed(double & steering_angle, double wheel_speed);
  bool reset();
  void halt();
};
}  // namespace tricycle_controller
#endif  // TRICYCLE_CONTROLLER__TRICYCLE_CONTROLLER_HPP_
